/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as ImageEditorRouteImport } from './routes/image-editor'
import { Route as CaptureZoomRouteImport } from './routes/capture-zoom'
import { Route as AreaSelectorRouteImport } from './routes/area-selector'
import { Route as AccentPopupRouteImport } from './routes/accent-popup'
import { Route as MainRouteImport } from './routes/_main'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MainStartupRouteImport } from './routes/_main.startup'
import { Route as MainSoundRouteImport } from './routes/_main.sound'
import { Route as MainLightsRouteImport } from './routes/_main.lights'
import { Route as MainDisplayRouteImport } from './routes/_main.display'
import { Route as MainDiagnosticsRouteImport } from './routes/_main.diagnostics'
import { Route as MainCompanionRouteImport } from './routes/_main.companion'
import { Route as MainCaptureRouteImport } from './routes/_main.capture'
import { Route as MainAccentRouteImport } from './routes/_main.accent'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageEditorRoute = ImageEditorRouteImport.update({
  id: '/image-editor',
  path: '/image-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureZoomRoute = CaptureZoomRouteImport.update({
  id: '/capture-zoom',
  path: '/capture-zoom',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaSelectorRoute = AreaSelectorRouteImport.update({
  id: '/area-selector',
  path: '/area-selector',
  getParentRoute: () => rootRouteImport,
} as any)
const AccentPopupRoute = AccentPopupRouteImport.update({
  id: '/accent-popup',
  path: '/accent-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MainStartupRoute = MainStartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => MainRoute,
} as any)
const MainSoundRoute = MainSoundRouteImport.update({
  id: '/sound',
  path: '/sound',
  getParentRoute: () => MainRoute,
} as any)
const MainLightsRoute = MainLightsRouteImport.update({
  id: '/lights',
  path: '/lights',
  getParentRoute: () => MainRoute,
} as any)
const MainDisplayRoute = MainDisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => MainRoute,
} as any)
const MainDiagnosticsRoute = MainDiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => MainRoute,
} as any)
const MainCompanionRoute = MainCompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => MainRoute,
} as any)
const MainCaptureRoute = MainCaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => MainRoute,
} as any)
const MainAccentRoute = MainAccentRouteImport.update({
  id: '/accent',
  path: '/accent',
  getParentRoute: () => MainRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accent-popup': typeof AccentPopupRoute
  '/area-selector': typeof AreaSelectorRoute
  '/capture-zoom': typeof CaptureZoomRoute
  '/image-editor': typeof ImageEditorRoute
  '/preview': typeof PreviewRoute
  '/accent': typeof MainAccentRoute
  '/capture': typeof MainCaptureRoute
  '/companion': typeof MainCompanionRoute
  '/diagnostics': typeof MainDiagnosticsRoute
  '/display': typeof MainDisplayRoute
  '/lights': typeof MainLightsRoute
  '/sound': typeof MainSoundRoute
  '/startup': typeof MainStartupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accent-popup': typeof AccentPopupRoute
  '/area-selector': typeof AreaSelectorRoute
  '/capture-zoom': typeof CaptureZoomRoute
  '/image-editor': typeof ImageEditorRoute
  '/preview': typeof PreviewRoute
  '/accent': typeof MainAccentRoute
  '/capture': typeof MainCaptureRoute
  '/companion': typeof MainCompanionRoute
  '/diagnostics': typeof MainDiagnosticsRoute
  '/display': typeof MainDisplayRoute
  '/lights': typeof MainLightsRoute
  '/sound': typeof MainSoundRoute
  '/startup': typeof MainStartupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_main': typeof MainRouteWithChildren
  '/accent-popup': typeof AccentPopupRoute
  '/area-selector': typeof AreaSelectorRoute
  '/capture-zoom': typeof CaptureZoomRoute
  '/image-editor': typeof ImageEditorRoute
  '/preview': typeof PreviewRoute
  '/_main/accent': typeof MainAccentRoute
  '/_main/capture': typeof MainCaptureRoute
  '/_main/companion': typeof MainCompanionRoute
  '/_main/diagnostics': typeof MainDiagnosticsRoute
  '/_main/display': typeof MainDisplayRoute
  '/_main/lights': typeof MainLightsRoute
  '/_main/sound': typeof MainSoundRoute
  '/_main/startup': typeof MainStartupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accent-popup'
    | '/area-selector'
    | '/capture-zoom'
    | '/image-editor'
    | '/preview'
    | '/accent'
    | '/capture'
    | '/companion'
    | '/diagnostics'
    | '/display'
    | '/lights'
    | '/sound'
    | '/startup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accent-popup'
    | '/area-selector'
    | '/capture-zoom'
    | '/image-editor'
    | '/preview'
    | '/accent'
    | '/capture'
    | '/companion'
    | '/diagnostics'
    | '/display'
    | '/lights'
    | '/sound'
    | '/startup'
  id:
    | '__root__'
    | '/'
    | '/_main'
    | '/accent-popup'
    | '/area-selector'
    | '/capture-zoom'
    | '/image-editor'
    | '/preview'
    | '/_main/accent'
    | '/_main/capture'
    | '/_main/companion'
    | '/_main/diagnostics'
    | '/_main/display'
    | '/_main/lights'
    | '/_main/sound'
    | '/_main/startup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MainRoute: typeof MainRouteWithChildren
  AccentPopupRoute: typeof AccentPopupRoute
  AreaSelectorRoute: typeof AreaSelectorRoute
  CaptureZoomRoute: typeof CaptureZoomRoute
  ImageEditorRoute: typeof ImageEditorRoute
  PreviewRoute: typeof PreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-editor': {
      id: '/image-editor'
      path: '/image-editor'
      fullPath: '/image-editor'
      preLoaderRoute: typeof ImageEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture-zoom': {
      id: '/capture-zoom'
      path: '/capture-zoom'
      fullPath: '/capture-zoom'
      preLoaderRoute: typeof CaptureZoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-selector': {
      id: '/area-selector'
      path: '/area-selector'
      fullPath: '/area-selector'
      preLoaderRoute: typeof AreaSelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accent-popup': {
      id: '/accent-popup'
      path: '/accent-popup'
      fullPath: '/accent-popup'
      preLoaderRoute: typeof AccentPopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/startup': {
      id: '/_main/startup'
      path: '/startup'
      fullPath: '/startup'
      preLoaderRoute: typeof MainStartupRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/sound': {
      id: '/_main/sound'
      path: '/sound'
      fullPath: '/sound'
      preLoaderRoute: typeof MainSoundRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/lights': {
      id: '/_main/lights'
      path: '/lights'
      fullPath: '/lights'
      preLoaderRoute: typeof MainLightsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/display': {
      id: '/_main/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof MainDisplayRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/diagnostics': {
      id: '/_main/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof MainDiagnosticsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/companion': {
      id: '/_main/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof MainCompanionRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/capture': {
      id: '/_main/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof MainCaptureRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/accent': {
      id: '/_main/accent'
      path: '/accent'
      fullPath: '/accent'
      preLoaderRoute: typeof MainAccentRouteImport
      parentRoute: typeof MainRoute
    }
  }
}

interface MainRouteChildren {
  MainAccentRoute: typeof MainAccentRoute
  MainCaptureRoute: typeof MainCaptureRoute
  MainCompanionRoute: typeof MainCompanionRoute
  MainDiagnosticsRoute: typeof MainDiagnosticsRoute
  MainDisplayRoute: typeof MainDisplayRoute
  MainLightsRoute: typeof MainLightsRoute
  MainSoundRoute: typeof MainSoundRoute
  MainStartupRoute: typeof MainStartupRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainAccentRoute: MainAccentRoute,
  MainCaptureRoute: MainCaptureRoute,
  MainCompanionRoute: MainCompanionRoute,
  MainDiagnosticsRoute: MainDiagnosticsRoute,
  MainDisplayRoute: MainDisplayRoute,
  MainLightsRoute: MainLightsRoute,
  MainSoundRoute: MainSoundRoute,
  MainStartupRoute: MainStartupRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MainRoute: MainRouteWithChildren,
  AccentPopupRoute: AccentPopupRoute,
  AreaSelectorRoute: AreaSelectorRoute,
  CaptureZoomRoute: CaptureZoomRoute,
  ImageEditorRoute: ImageEditorRoute,
  PreviewRoute: PreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
