/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartupRouteImport } from './routes/startup'
import { Route as SoundRouteImport } from './routes/sound'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as LightsRouteImport } from './routes/lights'
import { Route as ImageEditorRouteImport } from './routes/image-editor'
import { Route as DisplayRouteImport } from './routes/display'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as CompanionRouteImport } from './routes/companion'
import { Route as CaptureZoomRouteImport } from './routes/capture-zoom'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as AreaSelectorRouteImport } from './routes/area-selector'
import { Route as AccentPopupRouteImport } from './routes/accent-popup'
import { Route as AccentRouteImport } from './routes/accent'
import { Route as IndexRouteImport } from './routes/index'

const StartupRoute = StartupRouteImport.update({
  id: '/startup',
  path: '/startup',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundRoute = SoundRouteImport.update({
  id: '/sound',
  path: '/sound',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LightsRoute = LightsRouteImport.update({
  id: '/lights',
  path: '/lights',
  getParentRoute: () => rootRouteImport,
} as any)
const ImageEditorRoute = ImageEditorRouteImport.update({
  id: '/image-editor',
  path: '/image-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayRoute = DisplayRouteImport.update({
  id: '/display',
  path: '/display',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanionRoute = CompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureZoomRoute = CaptureZoomRouteImport.update({
  id: '/capture-zoom',
  path: '/capture-zoom',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const AreaSelectorRoute = AreaSelectorRouteImport.update({
  id: '/area-selector',
  path: '/area-selector',
  getParentRoute: () => rootRouteImport,
} as any)
const AccentPopupRoute = AccentPopupRouteImport.update({
  id: '/accent-popup',
  path: '/accent-popup',
  getParentRoute: () => rootRouteImport,
} as any)
const AccentRoute = AccentRouteImport.update({
  id: '/accent',
  path: '/accent',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accent': typeof AccentRoute
  '/accent-popup': typeof AccentPopupRoute
  '/area-selector': typeof AreaSelectorRoute
  '/capture': typeof CaptureRoute
  '/capture-zoom': typeof CaptureZoomRoute
  '/companion': typeof CompanionRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/display': typeof DisplayRoute
  '/image-editor': typeof ImageEditorRoute
  '/lights': typeof LightsRoute
  '/preview': typeof PreviewRoute
  '/sound': typeof SoundRoute
  '/startup': typeof StartupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accent': typeof AccentRoute
  '/accent-popup': typeof AccentPopupRoute
  '/area-selector': typeof AreaSelectorRoute
  '/capture': typeof CaptureRoute
  '/capture-zoom': typeof CaptureZoomRoute
  '/companion': typeof CompanionRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/display': typeof DisplayRoute
  '/image-editor': typeof ImageEditorRoute
  '/lights': typeof LightsRoute
  '/preview': typeof PreviewRoute
  '/sound': typeof SoundRoute
  '/startup': typeof StartupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accent': typeof AccentRoute
  '/accent-popup': typeof AccentPopupRoute
  '/area-selector': typeof AreaSelectorRoute
  '/capture': typeof CaptureRoute
  '/capture-zoom': typeof CaptureZoomRoute
  '/companion': typeof CompanionRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/display': typeof DisplayRoute
  '/image-editor': typeof ImageEditorRoute
  '/lights': typeof LightsRoute
  '/preview': typeof PreviewRoute
  '/sound': typeof SoundRoute
  '/startup': typeof StartupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accent'
    | '/accent-popup'
    | '/area-selector'
    | '/capture'
    | '/capture-zoom'
    | '/companion'
    | '/diagnostics'
    | '/display'
    | '/image-editor'
    | '/lights'
    | '/preview'
    | '/sound'
    | '/startup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accent'
    | '/accent-popup'
    | '/area-selector'
    | '/capture'
    | '/capture-zoom'
    | '/companion'
    | '/diagnostics'
    | '/display'
    | '/image-editor'
    | '/lights'
    | '/preview'
    | '/sound'
    | '/startup'
  id:
    | '__root__'
    | '/'
    | '/accent'
    | '/accent-popup'
    | '/area-selector'
    | '/capture'
    | '/capture-zoom'
    | '/companion'
    | '/diagnostics'
    | '/display'
    | '/image-editor'
    | '/lights'
    | '/preview'
    | '/sound'
    | '/startup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccentRoute: typeof AccentRoute
  AccentPopupRoute: typeof AccentPopupRoute
  AreaSelectorRoute: typeof AreaSelectorRoute
  CaptureRoute: typeof CaptureRoute
  CaptureZoomRoute: typeof CaptureZoomRoute
  CompanionRoute: typeof CompanionRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  DisplayRoute: typeof DisplayRoute
  ImageEditorRoute: typeof ImageEditorRoute
  LightsRoute: typeof LightsRoute
  PreviewRoute: typeof PreviewRoute
  SoundRoute: typeof SoundRoute
  StartupRoute: typeof StartupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/startup': {
      id: '/startup'
      path: '/startup'
      fullPath: '/startup'
      preLoaderRoute: typeof StartupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound': {
      id: '/sound'
      path: '/sound'
      fullPath: '/sound'
      preLoaderRoute: typeof SoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lights': {
      id: '/lights'
      path: '/lights'
      fullPath: '/lights'
      preLoaderRoute: typeof LightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/image-editor': {
      id: '/image-editor'
      path: '/image-editor'
      fullPath: '/image-editor'
      preLoaderRoute: typeof ImageEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display': {
      id: '/display'
      path: '/display'
      fullPath: '/display'
      preLoaderRoute: typeof DisplayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companion': {
      id: '/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof CompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture-zoom': {
      id: '/capture-zoom'
      path: '/capture-zoom'
      fullPath: '/capture-zoom'
      preLoaderRoute: typeof CaptureZoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/area-selector': {
      id: '/area-selector'
      path: '/area-selector'
      fullPath: '/area-selector'
      preLoaderRoute: typeof AreaSelectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accent-popup': {
      id: '/accent-popup'
      path: '/accent-popup'
      fullPath: '/accent-popup'
      preLoaderRoute: typeof AccentPopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accent': {
      id: '/accent'
      path: '/accent'
      fullPath: '/accent'
      preLoaderRoute: typeof AccentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccentRoute: AccentRoute,
  AccentPopupRoute: AccentPopupRoute,
  AreaSelectorRoute: AreaSelectorRoute,
  CaptureRoute: CaptureRoute,
  CaptureZoomRoute: CaptureZoomRoute,
  CompanionRoute: CompanionRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  DisplayRoute: DisplayRoute,
  ImageEditorRoute: ImageEditorRoute,
  LightsRoute: LightsRoute,
  PreviewRoute: PreviewRoute,
  SoundRoute: SoundRoute,
  StartupRoute: StartupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
